server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
    gateway:
      server:
        webflux:
          routes:
            - id: course-service-smoke
              uri: lb://course-service
              predicates:
                - Path=/_internal/smoke/course
              filters:
                - SetPath=/internal/info
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: student-service
              uri: lb://student-service
              predicates:
                - Path=/api/v1/students/**
            - id: course-service
              uri: lb://course-service
              predicates:
                - Path=/api/v1/courses/**,/api/v1/semesters/**,/api/v1/teachers/**,/api/v1/course-offerings/**
            - id: enrollment-write-service
              uri: lb://enrollment-service
              predicates:
                - Path=/api/v1/enrollments/**,/api/v1/enrollment-requests/**
                - Method=POST,DELETE
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: ${GATEWAY_ENROLLMENT_REPLENISH_RATE:5}
                    redis-rate-limiter.burstCapacity: ${GATEWAY_ENROLLMENT_BURST_CAPACITY:10}
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@enrollmentKeyResolver}"
            - id: enrollment-read-service
              uri: lb://enrollment-service
              predicates:
                - Path=/api/v1/enrollments/**,/api/v1/enrollment-requests/**
                - Method=GET

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    phase: 8-frontend-gateway

campus:
  security:
    jwt:
      secret-base64: ${JWT_SECRET_BASE64}
      issuer: ${JWT_ISSUER:https://campus-enroll.local}
      audience: ${JWT_AUDIENCE:campus-enroll-api}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
